baseURL = "/ib-psych/"
languageCode = "en-US"
defaultContentLanguage = "en"
disableLanguageSwitchingButton=true

title = "IB psych activities"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/hejtmy/ib-psych/tree/master/content/"
  description = "IB psychology notes with activities"
  author = "Lukáš Hejtmánek"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/hejtmy/ib-psych"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30